<?php
/*
 * MotaWord
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/21/2016
 */

namespace MotaWord\Models;

use MotaWord\Models\BaseEnum;

class PaymentMethodEnum extends BaseEnum {
    /**
     * TODO: Write general description for this element
     */
    const CORPORATE = "corporate";

    /**
     * TODO: Write general description for this element
     */
    const CLIENT = "client";

}