<?php
/*
 * MotaWord
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/21/2016
 */

namespace MotaWord;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'https://api.motaword.com';

    public static $clientID;
    public static $clientSecret;

    //The OAuth 2.0 access token to be set before API calls. Generated automatically by MotaWord\APIHelper::generateAccessToken()
    public static $oAuthAccessToken;

}